#!/usr/bin/make -f

TOP := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))

image-name=ipfs/go-ipfs
tag=latest
image=$(image-name):$(tag)

name=ipfs_host

# IPFS env
ipfs_staging=${TOP}staging
ipfs_data=${TOP}data

registry=apifocal
runargs=--publish-all
